### ISSUE TITLE
The definition in the AR classes?? 

### ISSUE THREAD

**Issue by cherifGsoul** [saada/yii2-factory-muffin#4]
I dont understand why the definitions are in the Active Record classes, I think they should be separate, definitions are not part of the application classes!!

**Comment by saada** [comment]
The reason for this design decision was because definitions, just like rules and labels and PHPDOC and relations, they all tend to change every time we perform migrations to the table corresponding to the model. So it's really convenient to place them inside the model.

Care to elaborate what the down-sides are to this approach?
Also I'd be more than happy to accept a pull-request given that you can provide strong arguments against this approach.

**Comment by cherifGsoul** [comment]
I think the downside is the coupling of tests code to the active record classe, the active record is already bloated of features :) , I said that because Im thinking about using the factory mufin just in tests context nothing else, in production we will have a code that has nothing to do with our application.
Sure I will help to make this project more powerful.

**Comment by saada** [comment]
Actually... you don't have to place your definitions in the models if you don't want to... It's purely a convenience... If you want you can add your definitions inline in your test suite..

``` php
<?php
$fm = new saada\FactoryMuffin\FactoryMuffin();
$fm->define('models\Message', array(
    'user_id'      => 'factory|models\User',
    'subject'      => 'sentence',
    'message'      => 'text',
    'phone_number' => 'randomNumber|8',
    'created'      => 'date|Ymd h:s',
    'slug'         => 'call|makeSlug|word',
), function ($object, $saved) {
    // we're taking advantage of the callback functionality here
    $object->message .= '!';
});

$fm->define('models\User', array(
    'username' => 'firstNameMale',
    'email'    => 'email',
    'avatar'   => 'imageUrl|400;600',
    'greeting' => RandomGreeting::get(),
    'four'     => function() {
        return 2 + 2;
    },
));
```

I'll this in the README and close this issue. Thanks for the feedback.

**Comment by saada** [comment]
Take a look here: https://github.com/saada/yii2-factory-muffin/commit/845c383e5dd56a2ec966d9f56f52c6961035f59e?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
@cherifGsoul

**Comment by cherifGsoul** [comment]
This is nice, thank you :+1:
