### ISSUE TITLE
Add composer version tag

### ISSUE THREAD

**Issue by sadovnik** [saada/yii2-factory-muffin#5]
Would be helpful if you add a version tag to the package so users don't have to set minimum-stability of their packages to dev.

**Comment by saada** [comment]
can you please make a PR? thanks

**Comment by sadovnik** [comment]
I can't because I don't have maintainer access to your repo.

This could be done like this:
1. Add tag
```
git tag 1.0.0
git push --tags
```

2. Go to the Packagist page: https://packagist.org/packages/saada/yii2-factory-muffin

3. Hit the "Update" button

You can also add GitHub hook so Packagist would update every time you push: https://packagist.org/about#how-to-update-packages

**Comment by saada** [comment]
Done! Thank you so much
