### ISSUE TITLE
Unable to use this package with stable minimum-stability

### ISSUE THREAD

**Issue by sadovnik** [saada/yii2-factory-muffin#7]
I still had no luck using this package with `stable` minimum-stability:

```
  Problem 1
    - Installation request for saada/yii2-factory-muffin ~1.0 -> satisfiable by saada/yii2-factory-muffin[1.0.0].
    - saada/yii2-factory-muffin 1.0.0 requires league/factory-muffin dev-master -> satisfiable by league/factory-muffin[dev-master] but these conflict with your requirements or minimum-stability.
```

Could we set some specific version of `league/factory-muffin` (`~3.0`) and drop the `minimum-stability` (because `stable` is the default setting)?

**Comment by saada** [comment]
When I wrote this, factory-muffin 3.0 was still in development. That's why it was setup this way.
Let me update it!

**Comment by saada** [comment]
https://github.com/saada/yii2-factory-muffin/commit/4d11b25f3ff70c68bc36969ca61479ab8cd6a0b0
